## Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split # for splitting dataset

In [15]:
# Importing the dataset
dataset_car = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data', header=None)
dataset_titanic = pd.read_csv('https://raw.githubusercontent.com/URI-CSC/461-fall-2020/master/assignments/assignment-1/titanic.csv', header=None)
col_len=len(dataset_titanic.index)
dataset_titanic=dataset_titanic.iloc[1:]#excludes the row names, that is in colomn 1 by default
print(dataset_titanic.head())

   0  1                                                  2       3   4  5  6  \
1  0  3                             Mr. Owen Harris Braund    male  22  1  0   
2  1  1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38  1  0   
3  1  3                              Miss. Laina Heikkinen  female  26  0  0   
4  1  1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35  1  0   
5  0  3                            Mr. William Henry Allen    male  35  0  0   

         7  
1     7.25  
2  71.2833  
3    7.925  
4     53.1  
5     8.05  


In [3]:
# for converting str to int
feature_len=dataset_titanic.shape[1]
dataset_len=col_len
indexes=[0,1,5,6]



#dataset_titanic.to_numeric(dataset_titanic[0],downcast='signed')


dataset_titanic[0]=dataset_titanic[0].astype('int')
dataset_titanic[1]=dataset_titanic[1].astype('int')
dataset_titanic[5]=dataset_titanic[5].astype('int')
dataset_titanic[6]=dataset_titanic[6].astype('int')

#for index,row in dataset_titanic.iterrows():
    
#for i in indexes:
   # for j in range (dataset_len):
        #temp=dataset_titanic[i][j]
        #temp=j
        #dataset_titanic[i][j]=int(temp)
#convert to float
f_indexes=[4, 7]
dataset_titanic[4]=dataset_titanic[4].astype('float')
dataset_titanic[7]=dataset_titanic[7].astype('float')
print(dataset_titanic.head)

<bound method NDFrame.head of      0  1                                                  2       3     4  5  \
1    0  3                             Mr. Owen Harris Braund    male  22.0  1   
2    1  1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0  1   
3    1  3                              Miss. Laina Heikkinen  female  26.0  0   
4    1  1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0  1   
5    0  3                            Mr. William Henry Allen    male  35.0  0   
..  .. ..                                                ...     ...   ... ..   
883  0  2                               Rev. Juozas Montvila    male  27.0  0   
884  1  1                        Miss. Margaret Edith Graham  female  19.0  0   
885  0  3                     Miss. Catherine Helen Johnston  female   7.0  1   
886  1  1                               Mr. Karl Howell Behr    male  26.0  0   
887  0  3                                 Mr. Patrick Dooley    male  32.0  0  

In [4]:
#proof above is in ints and floats do not delete
#test if int
print(type(dataset_titanic[4].iloc[0]))
print(dataset_titanic[4].iloc[0])#4 represents horizonatal movement

<class 'numpy.float64'>
22.0


In [6]:
# Separating the data into X and Y
X = dataset_titanic.iloc[:, [1,3,4,5,6,7]].values
y = dataset_titanic.iloc[:,:1].values
print (X.shape, y.shape)

def unique_vals(rows, col):
    """Find the unique values for a column in a dataset."""
    return set([row[col] for row in rows])
unique_vals(X, 0)
##unique_vals(X, 1)
##unique_vals(X, 2)
##unique_vals(X, 3)
##unique_vals(X, 4)
##unique_vals(X, 5)
print(type(X))

(887, 6) (887, 1)
<class 'numpy.ndarray'>


In [7]:
print(X)

[[3 'male' 22.0 1 0 7.25]
 [1 'female' 38.0 1 0 71.2833]
 [3 'female' 26.0 0 0 7.925]
 ...
 [3 'female' 7.0 1 2 23.45]
 [1 'male' 26.0 0 0 30.0]
 [3 'male' 32.0 0 0 7.75]]


In [8]:
def isNum(number):
    if((type(number)==type(5)) or (type(number)==type(4.4))):
        return True
    else: 
        return False
print(isNum('1'))

False


In [9]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(709, 6) (178, 6) (709, 1) (178, 1)


In [10]:

# Column labels.
# These are used only to print the tree.
header = [ "Pclass", "Sex", "Age", "sibilings, spouses aboard", "Parents/children Aboard", "fare"]

## Object creation

In [11]:
class QuestionCreator:
    def __init__(self, feat, value):
        self.feature=feat
        self.value=value
        
    def do(self, example):#col->feature, val->numeric valur
        val=example[self.feature]# if error or no sense may have to subsitute for sepal_l, sepal_w, etc.
        if isNum(val):
            return val >= self.value #translation- example >= sepal_l, sepal_w etc
        else: 
            return val == self.value
        
    def __repr__(self):
        # This is just a helper method to print
        # the question in a readable format.
        condition = "=="
        if isNum(self.value):
            condition = ">="
        return "Is %s %s %s?" % (
            header[self.feature], condition, str(self.value))

## demonstation purposes only
q=QuestionCreator(0,'poo')
print(q)

In [12]:
X_train

array([[3, 'male', 30.0, 0, 0, 7.25],
       [1, 'female', 38.0, 0, 0, 79.2],
       [3, 'female', 2.0, 0, 1, 12.2875],
       ...,
       [1, 'male', 32.0, 0, 0, 30.5],
       [2, 'male', 28.0, 0, 0, 13.5],
       [3, 'male', 19.0, 0, 0, 10.1708]], dtype=object)

In [13]:
def partition(rows, question):
    
    true_rows, false_rows = [ ], [ ]
    for i in rows:
        if question.do(i):
            true_rows.append(i)
        else:
            false_rows.append(i)
    #print("true_rows", true_rows)
    #print("false Rows", false_rows)
    return true_rows, false_rows
    
partition(X_train, QuestionCreator(0,3))

([array([3, 'male', 30.0, 0, 0, 7.25], dtype=object),
  array([3, 'female', 2.0, 0, 1, 12.2875], dtype=object),
  array([3, 'male', 48.0, 0, 0, 7.8542], dtype=object),
  array([3, 'male', 69.0, 0, 0, 14.5], dtype=object),
  array([3, 'male', 17.0, 0, 0, 8.6625], dtype=object),
  array([3, 'male', 40.0, 0, 0, 7.225], dtype=object),
  array([3, 'male', 39.0, 0, 0, 7.25], dtype=object),
  array([3, 'male', 40.0, 0, 0, 7.8958], dtype=object),
  array([3, 'male', 20.0, 1, 0, 15.5], dtype=object),
  array([3, 'male', 21.0, 0, 0, 7.925], dtype=object),
  array([3, 'female', 21.0, 0, 0, 7.75], dtype=object),
  array([3, 'male', 45.5, 0, 0, 7.225], dtype=object),
  array([3, 'female', 14.0, 1, 0, 11.2417], dtype=object),
  array([3, 'male', 17.0, 1, 1, 7.2292], dtype=object),
  array([3, 'female', 31.0, 1, 0, 18.0], dtype=object),
  array([3, 'male', 24.0, 2, 0, 23.25], dtype=object),
  array([3, 'male', 30.0, 0, 0, 8.05], dtype=object),
  array([3, 'female', 18.0, 1, 0, 15.5], dtype=object),
 

## Main functions

In [14]:
def find_best_split(rows):#rows aka X_train so 0-3 or each feature, 4 times
    n_features = len(rows[0])- 1  # number of columns, i.e. this line makes it 4 times
    col_len=len(rows)-1
    for col in range(n_features):  # for each feature
        values = set([row[col] for row in rows])
        col_len=len(rows)-1
        for val in range(col_len):  # for each value

            question = QuestionCreator(col, rows[val][col])
            
            partition(rows,question)
            print(question)
#print(len(X_train[0]))
#print(len(X_train))
find_best_split(X_train)

Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 2?
Is Pclass >= 1?
Is Pclass >= 2?
Is Pclass >= 1?
Is Pclass >= 1?
Is Pclass >= 2?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 1?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 2?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclass >= 2?
Is Pclass >= 1?
Is Pclass >= 1?
Is Pclass >= 3?
Is Pclass >= 3?
Is Pclass >= 1?
Is Pclas